### ISSUE TITLE
Inquiry on Deploying Multi-Robot Exploration and Communication in the Real World

### ISSUE THREAD

**Issue by meilaoliu** [caochao39/mtare_planner#3]
你好，非常感谢你们的开源。仿真我已经跑通了，但是想要在实物多个机器人上部署M-Tare来进行多机探索该怎么实现？是否可以按照Tare中实物部署的步骤实现。还有就是实物中多个机器人之间的通信该如何实现？运行仿真时多台电脑之间通过网线与交换机连接可以实现通信，但是连接同一个无线路由器就无法通信了，是不是无线wifi的带宽与稳定性无法满足造成的。我看项目官网是建议用自组网的方式，是否只有这一种解决办法？

Hello, thank you very much for your great open-source work. I have successfully run the simulation, but I am wondering how to deploy M-Tare on multiple robots for multi-robot exploration in the real world. Can I follow the steps for deploying in the real world as outlined in Tare project ? Also, how can communication between multiple robots in the real world be achieved? During simulation, communication between multiple computers is possible through Ethernet cables and a switch, but when connecting to the same wireless router, communication is not possible. Is this because the bandwidth and stability of wireless WiFi are insufficient? I saw on the project's official website that it is recommended to useWireless ad hoc network. Is this the only solution?

**Comment by caochao39** [comment]
Hello, based on our experience, we recommend using a wireless ad hoc network. There may be other viable communication solutions available. The instructions for deploying TARE should also be largely applicable to M-TARE. Please don't hesitate to reach out if you encounter any specific issues during the deployment. Thank you!

**Comment by huahai2022** [comment]
> 你好，非常感谢你们的开源。仿真我已经跑通了，但是想要在实物多个机器人上部署M-Tare来进行多机探索该怎么实现？是否可以按照Tare中实物部署的步骤实现。还有就是实物中多个机器人之间的通信该如何实现？运行仿真时多台电脑之间通过网线与交换机连接可以实现通信，但是连接同一个无线路由器就无法通信了，是不是无线wifi的带宽与稳定性无法满足造成的。我看项目官网是建议用自组网的方式，是否只有这一种解决办法？
> 
> Hello, thank you very much for your great open-source work. I have successfully run the simulation, but I am wondering how to deploy M-Tare on multiple robots for multi-robot exploration in the real world. Can I follow the steps for deploying in the real world as outlined in Tare project ? Also, how can communication between multiple robots in the real world be achieved? During simulation, communication between multiple computers is possible through Ethernet cables and a switch, but when connecting to the same wireless router, communication is not possible. Is this because the bandwidth and stability of wireless WiFi are insufficient? I saw on the project's official website that it is recommended to useWireless ad hoc network. Is this the only solution?

你好，目前docker貌似无法拉取镜像，请问你能帮忙把拉取到的镜像转发给我吗，或者上传云盘，万分感激
